'use client';
import localFont from "next/font/local";
import "./globals.css";
import "toastr/build/toastr.min.css";
import AuthProvider from "../extras/authcontext";
import AlertProvider from "@/extras/alertcontext";
import MenuProvider from "@/extras/menucontext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AlertProvider>
          <AuthProvider>
            <MenuProvider>
              {children}
            </MenuProvider>
          </AuthProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
